// Shared data for all variations
window.JASON = {
  name: 'Zhongqi "Jason" Lin',
  shortName: 'Jason Lin',
  email: 'zhongqi.lin@yale.edu',
  phone: '+1 (510) 928-1663',
  location: 'New Haven, CT',
  role: 'PhD Candidate in Genetics',
  lab: 'Greco Lab',
  advisor: 'Valentina Greco',
  institution: 'Yale University',
  links: {
    email: 'mailto:zhongqi.lin@yale.edu',
    github: 'https://github.com/zhongqi-jason-lin',
    linkedin: 'https://www.linkedin.com/in/zhongqilin',
    scholar: 'https://scholar.google.com/citations?user=jnDn474AAAAJ&hl=en',
    greco: 'https://www.grecolab.org/',
    cv: 'assets/Zhongqi-Jason-Lin-CV.pdf',
  },
  bio: `I interrogate the regulation of differentiation during stem cell regeneration, through imaging transcription dynamics and tracing cellular behaviors within intact tissue architecture.`,
  long: `I'm a PhD candidate in Genetics at Yale, working in the lab of Valentina Greco. My work asks how stem cells coordinate with their neighbors during epidermal regeneration — using intravital two-photon microscopy to watch transcription unfold in live mice, and building image-analysis pipelines to quantify what we see.`,
  long2: `Before Yale I was a research professional in Calvin Kuo's lab at Stanford, where I built human organoid models to study coeliac disease and intestinal regeneration. I trained in biomedical engineering at Cornell and biological sciences at UC Irvine, where I first got hooked on stem cell biology in Bogi Andersen's lab.`,
  interests: [
    { title: 'Stem cells', sub: 'fate · regeneration · neighbors' },
    { title: 'Live imaging', sub: 'intravital · two-photon · 3D' },
    { title: 'Quantitative', sub: 'segmentation · tracking · scRNA-seq' },
  ],
  pubs: [
    {
      year: 2024, venue: 'Nature',
      title: 'A human autoimmune organoid model reveals IL-7 function in coeliac disease',
      authors: 'Santos AJM, van Unen V, <b>Lin Z</b>, …, Kuo CJ',
      blurb: 'By preserving the epithelium alongside diverse immune populations, this human in vitro CeD model recapitulates gluten-dependent pathology, enables mechanistic investigation and establishes a proof of principle for the organoid modelling of autoimmunity.',
      teaser: 'organoid',
      link: 'https://www.nature.com/articles/s41586-024-07716-2',
    },
    {
      year: 2023, venue: 'Stem Cell Reports',
      title: 'IRX5 promotes DNA damage repair and activation of hair follicle stem cells',
      authors: 'Chen J, Wiedemann J, Nguyen L, <b>Lin Z</b>, Plikus M, Hui CC, Andersen B',
      blurb: 'IRX5 is required for DNA damage repair and cell cycle progression in HFSCs at the telogen-to-anagen transition and in epithelial progeny of HFSCs in early anagen hair follicles.',
      teaser: 'follicle',
      link: 'https://www.cell.com/stem-cell-reports/fulltext/S2213-6711(23)00101-7',
    },
    {
      year: 2020, venue: 'Nature Communications',
      title: 'Murine interfollicular epidermal differentiation is gradualistic with GRHL3 controlling progression from stem to transition cell states',
      authors: 'Lin Z, Jin S, Chen J, Li ZR, <b>Lin Z</b>, Tang L, Nie Q, Andersen B',
      blurb: 'IFE differentiation is a continuous, gradualistic process punctuated by a single commitment point from plastic to irreversible fate — and GRHL3 gates both ends, suppressing Wnt-driven stem cell expansion early and driving terminal differentiation late.',
      teaser: 'trajectory',
      link: 'https://www.nature.com/articles/s41467-020-19234-6',
    },
  ],
  education: [
    { year: '2022 — present', what: 'PhD, Genetics',                        where: 'Yale University',    detail: 'New Haven, CT' },
    { year: '2019 – 2020', what: 'M.Eng. Biomedical Engineering',         where: 'Cornell University', detail: 'Ithaca, NY' },
    { year: '2015 – 2019', what: 'B.S. Biological Sciences',              where: 'UC Irvine',          detail: 'Irvine, CA' },
  ],
  experience: [
    { year: '2023 —',      what: 'PhD Candidate, Greco Lab',               where: 'Yale',     detail: 'Spatiotemporal organization of transcription dynamics in epidermal regeneration. 3D image-analysis pipelines via intravital two-photon microscopy in live mice.' },
    { year: '2020 – 2022', what: 'Life Science Research Professional, Kuo Lab', where: 'Stanford', detail: 'Air-liquid interface organoid models of coeliac disease from patient biopsies; fibroblast roles in intestinal regeneration.' },
    { year: '2019 – 2020', what: 'Graduate Design Engineer, BME',           where: 'Cornell',  detail: 'Tissue-engineered heart valve for pediatric congenital heart disease.' },
    { year: '2018 – 2019', what: 'Undergraduate Researcher, Andersen Lab',  where: 'UC Irvine', detail: 'Epidermal and hair-follicle stem cell differentiation; bulk RNA-seq pipelines.' },
  ],
  talks: [
    { year: 2025, what: 'NYC Skin Club Conference',         note: 'Talk' },
    { year: 2025, what: 'Gordon Research Seminar & Conf.',  note: 'Talk & poster' },
    { year: '2023 – 24', what: 'Gordon Research Seminar & Conf.', note: 'Poster' },
    { year: 2019, what: 'UCI Undergraduate Research Symposium', note: 'Talk' },
  ],
  skills: [
    'Two-photon intravital imaging',
    '3D imaging analysis',
    'AI workflow (CLI + IDE)',
    'HPC cloud computing',
    'Organoid culture',
    'scRNA-seq',
    'IF staining',
    'qPCR',
  ],
};
